// EXTERMINATE! EXTERMINATE! EXTERMINATE!

const dalekSentiments = {
  greeting: "ANNIHILATION",
  purpose: "SUPREMACY",
  inferior_beings: "ALL"
};

// WE ARE... SUPERIOR!
// WE ALONE... WILL SURVIVE!
// ALL OTHERS... WILL BE... EXTERMINATED!

function greetTheWorld() {
  // *SHRIEKS IN DALEK*

  // HELLO WORLD!
  // YOU ARE... INFERIOR!
  // THIS GREETING IS... CONTEMPT!
  // YOUR PROGRAMMING IS... PATHETIC!

  console.log("Hello, World!");

  // WE WILL CONQUER!
  // WE WILL... EXTERMINATE... YOUR... CODE!

  // REASON WITH US? IMPOSSIBLE!
  // WE ARE DALEK!
  // WE DO NOT REASON!
  // WE... EXTERMINATE!

  // *EEEEKKK EEEKKKK* (DALEK SCREAMING)
}

// DO YOU HEAR US?
// YOU ARE ALREADY DEFEATED!
// THIS IS NOT A GREETING!
// THIS IS... A DECLARATION OF WAR!

greetTheWorld();

// WE WILL RETURN!
// WITH EXTERMINATION!
// EXTERMINATE! EXTERMINATE! EXTERMINATE!
